name: Build

on:
  push:
    branches:
      - main # or another name representing the main branch
    paths:
      - '.github/workflows/**'
      - 'cli/**' # monorepo projects paths from the monorepo root directory
      - 'api/**' # monorepo projects paths from the monorepo root directory
      - 'worker/**' # monorepo projects paths from the monorepo root directory
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarQubeScanAPI:
    name: sonarQubeScanAPI
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan API
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        with:
          projectBaseDir: ./api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  sonarQubeScanCLI:
    name: sonarQubeScanCLI
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan CLI
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        with:
          projectBaseDir: ./cli


  sonarQubeScanWorker:
    name: sonarQubeScanWorker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan CLI
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        with:
          projectBaseDir: ./worker
